-- Migrate Role enum: ADMIN/SENDER/DRIVER -> SUPER_ADMIN/ADMIN/EXPEDITEUR/LIVREUR/CLIENT
CREATE TYPE "Role_new" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'EXPEDITEUR', 'LIVREUR', 'CLIENT');

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User"
  ALTER COLUMN "role" TYPE "Role_new"
  USING (
    CASE "role"::text
      WHEN 'ADMIN' THEN 'ADMIN'
      WHEN 'SENDER' THEN 'EXPEDITEUR'
      WHEN 'DRIVER' THEN 'LIVREUR'
      WHEN 'SUPER_ADMIN' THEN 'SUPER_ADMIN'
      WHEN 'EXPEDITEUR' THEN 'EXPEDITEUR'
      WHEN 'LIVREUR' THEN 'LIVREUR'
      WHEN 'CLIENT' THEN 'CLIENT'
      ELSE 'CLIENT'
    END
  )::"Role_new";

DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'CLIENT'::"Role";
